version: "3.9"

services:
  helicone:
    image: helicone/helicone-all-in-one:latest
    container_name: helicone
    ports:
      - "3000:3000"
      - "8585:8585"
      - "9080:9080"
    restart: unless-stopped
